seed: 42


fasta_path: "/home/maxime/Nucleoseq/demo/sequences/satellites.fa"

#Model
model_path: "/home/maxime/Nucleoseq/demo/test/MNase_17chroms_CORRECTED_1.5prctCovered_globalWeightsOptim_20260303_142239/best.h5"

output_root: null #Default is model_path
experiment_name: "synthetic_satellites"


target_length: 3000
output_idx: 2
batch_size: 1024


n_perm: 1000
kmer_conservation: 2


show_perm_envelope: true


save_perm_profiles: true